galaxy_info:
  author: Shoma Nishitateno
  description: Installs and configures L2TP/IPsec server
  license: "license MIT"
  min_ansible_version: "1.8"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags: []