networks:
  back-tier:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  pg_data:
  srv1c_home:
  srv1c_conf:

services:
  postgresql:
    image: img_pg1c
    ports:
      - 5432:5432
    hostname: pg1c
    networks:
      back-tier:
        ipv4_address: 172.20.0.5
    volumes:
      - pg_data:/var/lib/pgpro/1c-15

  server-1c:
    image: img_server1c
    ports:
      - 1540-1541:1540-1541
      - 1560-1591:1560-1591
    hostname: server1c
    networks:
      back-tier:
        ipv4_address: 172.20.0.3
    env_file: .env
    depends_on:
      - postgresql
    volumes:
      - srv1c_home:/home/usr1cv8
      - srv1c_conf:/opt/1cv8