---
# Setup/install tasks.
- name: Ensure L2TP/IPSec is installed on system.
  apt:
    name: "{{ l2tp_ipsec_server_packages }}"
    state: present

# Configure strongswan tasks.
- name: Copy ipsec configuration in place.
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy pre-shared-key in place.
  template:
    src: ipsec.secrets.j2
    dest: /etc/ipsec.secrets
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy credential file in place.
  template:
    src: chap-secrets.j2
    dest: /etc/ppp/chap-secrets
    mode: 00600
  notify:
    - restart vpn-server

# Configure xl2tpd tasks.
- name: Copy xl2tpd config file in place.
  template:
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy xl2tpd option file in place.
  template:
    src: options.xl2tpd.j2
    dest: /etc/ppp/options.xl2tpd
    mode: 00600
  notify:
    - restart vpn-server

- name: Ensure VPN services is started and enabled to start at boot.
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ l2tp_ipsec_server_packages }}"