---
- name: Check all systems are ready
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - name: set docker context
      local_action: shell docker context create "{{ inventory_hostname }}" --docker "host=ssh://ubuntu@{{ ansible_host }}"
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

- name: Setup 1c server
  hosts: 1c_srvr
  become: true
  vars_files:
    - vars.yml
  roles:
    - ufw
    - osupgrade
    - docker_install
    - l2tp-ipsec-server
  # tasks:
  #   - name: make app directories
  #     ansible.builtin.file:
  #       path: "{{ item }}"
  #       state: directory
  #       mode: '0755'
  #     loop: "{{ app_directories }}"