---
ufw_rules:
  # Set logging
  - logging: "low"
  # Allow OpenSSH
  - rule: allow
    name: OpenSSH
  # Allow L2TP traffic
  - rule: allow
    to_port: '1701'
    proto: udp
    direction: in
  - rule: allow
    to_port: '500'
    proto: udp
  - rule: allow
    to_port: '4500'
    proto: udp
  - rule: allow
    proto: esp
  - rule: allow
    proto: ah

# vpn-server
l2tp_ipsec_PSK: vpn
l2tp_ipsec_server_local_ip: 192.168.40.1
l2tp_ipsec_server_ip_range: 192.168.40.129-192.168.40.140
l2tp_ipsec_server_users:
  - { username: user1, password: password1 }
  - { username: user2, password: password2 }

app_directories:
  - {path: /opt/1C/srv1c, owner: lxd, group: netdev}
  - {path: /opt/1C/usr1c, owner: lxd, group: netdev}
  - {path: /opt/1C/pg_data, owner: lxd, group: netdev, mode: "0775"}